TIEscola/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from .views import (
    listar_chamadas, 
    listar_ativos, 
    index, 
    ativo_detail_view,
    chamada_detail_view, 
    situacao_chart, 
    prioridade_chart,
    status_chart,
    tipo_chart,
    marca_chart,
    valores_estimados_chart,
    associacao_equipamento_chamada_chart,
    equipamentos_associados_por_chamada_chart,
    ExportarChamadaCSVView,
    ExportarAtivoCSVView,
    ExportarJSONChamadaView,
    ExportarJSONAtivoTIView,
    ExportarXMLChamadaView,
    ExportarXMLAtivoTIView,
    data_export,
    data_import,
    fazer_logout,
    adicionar_comentario_view,
    exportar_qrcodes_para_pdf,
    exportar_qrcode_para_pdf,
    chamadas_por_equipamento,
    pagina_chamadas_por_equipamento,
    chamadas_por_sala_chart,
    chamadas_por_data_chart,
    manutencoes_por_equipamento,
    pagina_manutencoes_por_equipamento,
    editar_ativo,
    editar_chamada,
    remover_chamada_lista,
    cadastrar_manutencao_ativo,
    editar_manutencao,
    editar_comentario,
    remover_ativo,
    remover_chamada,
    remover_comentario,
    remover_manutencao,
    business_intelligence,
    associar_ativos_chamada,
    associar_ativos_chamada_especifica,
    associar_chamadas_geral_ativo,
    desassociar_ativo_chamada,
    get_ativos_disponiveis,
    get_chamadas_disponiveis,
    associar_chamadas_ativo
)
from django.urls import path
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('get-ativos-disponiveis/', get_ativos_disponiveis, name='get_ativos_disponiveis'),
    path('get_chamadas_disponiveis/', get_chamadas_disponiveis, name='get_chamadas_disponiveis'),
    path('associar_ativos_chamada/', associar_ativos_chamada, name='associar_ativos_chamada'),
    path('associar_chamadas_geral_ativo/', associar_chamadas_geral_ativo, name='associar_chamadas_geral_ativo'),
    path('associar_chamadas_ativo/<int:ativo_id>', associar_chamadas_ativo, name='associar_chamadas_ativo'),
    path('associar_ativos_chamada_especifica/<int:chamada_id>', associar_ativos_chamada_especifica, name='associar_ativos_chamada_especifica'),
    path('desassociar_ativo_chamada/<int:chamada_id>/<int:ativo_id>', desassociar_ativo_chamada, name='desassociar_ativo_chamada'),
    path('editar_chamada/<str:id>/', editar_chamada, name='editar_chamada'),
    path('editar_ativo/<str:codigo>/', editar_ativo, name='editar_ativo'),
    path('editar_manutencao/<int:id>/<int:codigo>', editar_manutencao, name='editar_manutencao'),
    path('cadastrar_manutencao_ativo/', cadastrar_manutencao_ativo, name='cadastrar_manutencao_ativo'),
    path('editar_comentario/<int:id>/<int:chamada_id>', editar_comentario, name='editar_comentario'),
    path('remover_ativo/<str:codigo>/', remover_ativo, name='remover_ativo'),
    path('remover_chamada/<int:id>/', remover_chamada, name='remover_chamada'),
    path('remover_chamada/<int:id>/<str:codigo>', remover_chamada_lista, name='remover_chamada_lista'),
    path('remover_comentario/<int:id>/<int:chamada_id>', remover_comentario, name='remover_comentario'),
    path('remover_manutencao/<int:id>/<str:codigo>', remover_manutencao, name='remover_manutencao'),
    path('pagina_manutencoes_por_equipamento/', pagina_manutencoes_por_equipamento, name='pagina_manutencoes_por_equipamento'),
    path('manutencoes_por_equipamento/', manutencoes_por_equipamento, name='manutencoes_por_equipamento'),
    path('pagina_chamadas_por_equipamento/', pagina_chamadas_por_equipamento, name='pagina_chamadas_por_equipamento'),
    path('chamadas_por_equipamento/', chamadas_por_equipamento, name='chamadas_por_equipamento'),
    path('chamadas_por_sala/', chamadas_por_sala_chart, name='chamadas_por_sala'),
    path('chamadas_por_data/', chamadas_por_data_chart, name='chamadas_por_data'),
    path('associacao_equipamento_chamada_chart/', associacao_equipamento_chamada_chart, name='associacao_equipamento_chamada_chart'),
    path('equipamentos_associados_por_chamada_chart/', equipamentos_associados_por_chamada_chart, name='equipamentos_associados_por_chamada_chart'),
    path('login/', LoginView.as_view(template_name='main/login.html'), name='login'),
    path('chamada/<int:id>/adicionar-comentario/', adicionar_comentario_view, name='adicionar_comentario'),
    path('exportar_qrcodes_pdf/', exportar_qrcodes_para_pdf, name='exportar_qrcodes_pdf'),
    path('exportar_qrcode_pdf/<int:ativo_id>', exportar_qrcode_para_pdf, name='exportar_qrcode_para_pdf'),
    path('exportar_chamadas_csv/', ExportarChamadaCSVView.as_view(), name='exportar_chamadas_csv'),
    path('exportar_ativos_csv/', ExportarAtivoCSVView.as_view(), name='exportar_ativos_csv'),
    path('exportar_chamadas_json/', ExportarJSONChamadaView.as_view(), name='exportar_chamadas_json'),
    path('exportar_ativos_json/', ExportarJSONAtivoTIView.as_view(), name='exportar_ativos_json'),
    path('exportar_chamadas_xml/', ExportarXMLChamadaView.as_view(), name='exportar_chamadas_xml'),
    path('exportar_ativos_xml/', ExportarXMLAtivoTIView.as_view(), name='exportar_ativos_xml'),
    path('exportar_dados/', data_export, name='exportar_dados'),
    path('importar_dados/', data_import, name='importar_dados'),
    path('ativo/<int:id>/', ativo_detail_view, name='ativo_detail'),
    path('chamada/<str:id>/', chamada_detail_view, name='chamada_detail'),
    path('tipo/', tipo_chart, name='tipo'),
    path('marca/', marca_chart, name='marca'),
    path('situacao/', situacao_chart, name='situacao'),
    path('valores_estimados/', valores_estimados_chart, name='valores_estimados'),
    path('status/', status_chart, name='status'),
    path('prioridade/', prioridade_chart, name='prioridade'),
    path('business_intelligence/', business_intelligence, name='business_intelligence'),
    path('chamadas/', listar_chamadas, name='listar_chamadas'),
    path('ativos/', listar_ativos, name='listar_ativos'),
    path('logout/', fazer_logout, name='logout'),
    path('', index, name='index'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class CategoriaProblema(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class AtivoTI(models.Model):
    codigo = models.CharField(max_length=50, unique=True)
    nome = models.CharField(max_length=50)
    foto = models.URLField(max_length=200, 
    	default='https://informaticacebrac.netlify.app/images/computer.png', 
    	null=True, blank=True)
    
    TIPOS_DE_ATIVOS = [
        ('Computador', 'Computador'),
        ('Periférico', 'Periférico'),
        ('Impressora', 'Impressora'),
        ('Eletrônico', 'Eletrônico'),
        ('Servidor', 'Servidor'),
        ('Roteador', 'Roteador'),
        ('Switch', 'Switch'),
        ('Outros', 'Outros'),
    ]
    tipo = models.CharField(max_length=25, choices=TIPOS_DE_ATIVOS, default='Computador')

    MARCAS = [
        ('Dell', 'Dell'),
        ('HP', 'HP'),
        ('Lenovo', 'Lenovo'),
        ('Cisco', 'Cisco'),
        ('Philco', 'Philco'),
        ('Philips', 'Philips'),
        ('Outra', 'Outra'),
    ]
    marca = models.CharField(max_length=25, choices=MARCAS, default='Outra')

    especificacoes = models.TextField(blank=True, null=True)

    SITUACOES = [
        ('Funcionando', 'Funcionando'),
        ('Danificado', 'Danificado'),
        ('Inutilizável', 'Inutilizável'),
    ]
    situacao = models.CharField(max_length=25, choices=SITUACOES, default='Funcionando')

    # Adicione outras propriedades relevantes, como número de série, data de aquisição, etc.
    numero_serie = models.CharField(max_length=50, blank=True, null=True)
    data_aquisicao = models.DateField(blank=True, null=True)
    valor_estimado = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def get_situacao_data(self):
        situacoes = dict(self.SITUACOES)
        data = []

        for situacao_key, situacao_label in situacoes.items():
            count = AtivoTI.objects.filter(situacao=situacao_key).count()
            data.append({'label': situacao_label, 'count': count})

        return data

    def get_tipo_data(self):
        tipos = dict(self.TIPOS_DE_ATIVOS)
        data = []

        for tipo_key, tipo_label in tipos.items():
            count = AtivoTI.objects.filter(tipo=tipo_key).count()
            data.append({'label': tipo_label, 'count': count})

        return data

    def get_marcas_data(self):
        marcas = dict(self.MARCAS)
        data = []

        for marca_key, marca_label in marcas.items():
            count = AtivoTI.objects.filter(marca=marca_key).count()
            data.append({'label': marca_label, 'count': count})

        return data

    def get_numero_chamadas(self):
        return self.chamada_set.count()

    def get_numero_manutencoes(self):
        return self.manutencaoativo_set.count()
    
    def __str__(self):
        return f'{self.nome}'

class Responsavel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cargo = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

class Chamada(models.Model):
    STATUS_CHOICES = [
        ('Aberta', 'Aberta'),
        ('Atribuida', 'Atribuida'),
        ('Resolvida', 'Resolvida'),
    ]

    PRIORIDADE_CHOICES = [
        ('Baixa', 'Baixa'),
        ('Média', 'Média'),
        ('Alta', 'Alta'),
    ]

    SALAS = [
        ('Marketing', 'Marketing'),
        ('Recepção', 'Recepção'),
        ('Sala 01', 'Sala 01'),
        ('Sala Pequena', 'Sala Pequena'),
        ('Sala Inglês', 'Sala Inglês'),
        ('Sala Saúde', 'Sala Saúde'),
        ('Laboratório Informática', 'Laboratório Informática'),
        ('Coordenadoria', 'Coordenadoria'),
        ('Comercial', 'Comercial'),
        ('CRA', 'CRA'),
    ]

    sala_origem = models.CharField(max_length=50, choices=SALAS, default='Laboratório Informática')
    descricao_problema = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Aberta')
    prioridade = models.CharField(max_length=10, choices=PRIORIDADE_CHOICES, default='Média')
    data_abertura = models.DateTimeField(auto_now_add=True)
    data_resolucao = models.DateTimeField(null=True, blank=True)
    responsavel = models.ForeignKey(Responsavel, on_delete=models.SET_NULL, null=True, blank=True)
    categoria_problema = models.ForeignKey(CategoriaProblema, on_delete=models.CASCADE)
    custo_reparo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ativo_ti = models.ForeignKey(AtivoTI, on_delete=models.CASCADE)

    def get_prioridade_data(self):
        prioridades = dict(self.PRIORIDADE_CHOICES)
        data = []

        for prioridade_key, prioridade_label in prioridades.items():
            count = Chamada.objects.filter(prioridade=prioridade_key).count()
            data.append({'label': prioridade_label, 'count': count})

        return data

    def get_status_data(self):
        status = dict(self.STATUS_CHOICES)
        data = []

        for status_key, status_label in status.items():
            count = Chamada.objects.filter(status=status_key).count()
            data.append({'label': status_label, 'count': count})

        return data

    def get_sala_origem_data(self):
        salas = dict(self.SALAS)
        data = []

        for salas_key, salas_label in salas.items():
            count = Chamada.objects.filter(sala_origem=salas_key).count()
            data.append({'label': salas_label, 'count': count})

        return data

    def __str__(self):
        return f'Chamada {self.id} - {self.status}'

class Comentario(models.Model):
    chamada = models.ForeignKey('Chamada', on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()
    data_publicacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comentário por {self.autor.username} em {self.data_publicacao}'

class ManutencaoAtivo(models.Model):
    ativo = models.ForeignKey(AtivoTI, on_delete=models.CASCADE)
    descricao = models.TextField()
    data_inicio = models.DateField()
    data_conclusao = models.DateField(null=True, blank=True)
    custo = models.DecimalField(max_digits=10, decimal_places=2)
    responsavel = models.ForeignKey(Responsavel, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Manutenção de {self.ativo.nome} - {self.data_inicio}"

class ChamadaAtivo(models.Model):
    chamada = models.ForeignKey(Chamada, on_delete=models.CASCADE)
    ativos = models.ManyToManyField(AtivoTI)

    def __str__(self):
        return f"{self.chamada} - {', '.join(str(ativo) for ativo in self.ativos.all())}"

main/templates/main/associar_ativos_chamada.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Associar Equipamentos{% endblock %}

{% block content %}
<div id="particles-js"></div>
<div class="ativo-item">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="menu-container-details">
        <div class="menu-items">
            <a class="btn-inicio" href="{% url 'index' %}">Início</a>
            <a class="btn-inicio" href="{% url 'listar_ativos' %}">Equipamentos</a>
            <a class="btn-inicio" href="{% url 'listar_chamadas' %}">Chamadas</a>
        </div>
    </div>

    <div class="codigo">
        <h1>Associar Equipamentos com Chamada</h1>
    </div>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn-login" type="submit">Cadastrar</button>
    </form>

    <script>
        $(document).ready(function() {
            $('#id_ativo').select2();
        });

        $(document).ready(function() {
            $('#id_ativo').attr('disabled', true); // Desabilita o campo Ativo inicialmente

            $('#id_chamada').change(function() {
                var chamadaId = $(this).val();

                $.ajax({
                    url: '{% url "get_ativos_disponiveis" %}',
                    data: {
                        'chamada_id': chamadaId
                    },
                    dataType: 'json',
                    success: function(data) {
                        $('#id_ativo').empty(); // Limpa as opções existentes

                        $.each(data.ativos, function(index, ativo) {
                            $('#id_ativo').append('<option value="' + ativo.id + '">' + ativo.nome + '</option>');
                        });

                        $('#id_ativo').attr('disabled', false); // Habilita o campo Ativo
                    }
                });
            });
        });
    </script>
</div>
<script src="{% static 'js/particles.js' %}"></script>
<script src="{% static 'js/load-particles.js' %}"></script>
{% endblock %}

main/templates/main/associar_chamadas_geral_ativo.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Associar Chamadas{% endblock %}

{% block content %}
<div id="particles-js"></div>
<div class="ativo-item">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="menu-container-details">
        <div class="menu-items">
            <a class="btn-inicio" href="{% url 'index' %}">Início</a>
            <a class="btn-inicio" href="{% url 'listar_ativos' %}">Equipamentos</a>
            <a class="btn-inicio" href="{% url 'listar_chamadas' %}">Chamadas</a>
        </div>
    </div>

    <div class="codigo">
        <h1>Associar Equipamento com Chamadas</h1>
    </div>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn-login" type="submit">Cadastrar</button>
    </form>

    <script>
        $(document).ready(function() {
            $('#id_chamadas').select2();
        });

        $(document).ready(function() {
            $('#id_chamadas').attr('disabled', true); // Desabilita o campo Ativo inicialmente

            $('#id_ativos').change(function() {
                var ativoId = $(this).val();

                $.ajax({
                    url: '{% url "get_chamadas_disponiveis" %}',
                    data: {
                        'ativo_id': ativoId
                    },
                    dataType: 'json',
                    success: function(data) {
                        $('#id_chamadas').empty(); // Limpa as opções existentes

                        $.each(data.chamadas, function(index, chamada) {
                            $('#id_chamadas').append('<option value="' + chamada.id + '">' + 'Chamada ' + chamada.id + ' - ' + chamada.status + '</option>');
                        });

                        $('#id_chamadas').attr('disabled', false); // Habilita o campo Ativo
                    }
                });
            });
        });
    </script>
</div>
<script src="{% static 'js/particles.js' %}"></script>
<script src="{% static 'js/load-particles.js' %}"></script>
{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Seu Título Padrão{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />  
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

main/templates/main/business_intelligence.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Business Intelligence{% endblock %}

{% block content %}
<div id="particles-js"></div>
<div class="ativo-item">
    <a class="btn-inicio" href="{% url 'index' %}">Início</a>
    <a class="btn-inicio" href="{% url 'listar_ativos' %}">Equipamentos</a>
    <a class="btn-inicio" href="{% url 'listar_chamadas' %}">Chamadas</a>
    <h1 class="title" style="margin-top: 15px; margin-bottom: 20px">Business Intelligence</h1>
    <a class="btn-export" href="{% url 'pagina_chamadas_por_equipamento' %}">Chamadas por Equipamento</a>
    <a class="btn-export" href="{% url 'chamadas_por_sala' %}">Chamadas por Sala</a>
    <a class="btn-export" href="{% url 'chamadas_por_data' %}">Chamadas por Data</a>
    <a class="btn-export" href="{% url 'associacao_equipamento_chamada_chart' %}">Chamadas Associadas por Equipamento</a>
    <a class="btn-export" href="{% url 'equipamentos_associados_por_chamada_chart' %}">Equipamentos Associados por Chamada</a>
    <a class="btn-export" href="{% url 'pagina_manutencoes_por_equipamento' %}">Manutenções por Equipamento</a>
    <a class="btn-export" href="{% url 'valores_estimados' %}">Valores dos Equipamentos</a>
    <a class="btn-export" href="{% url 'situacao' %}">Situação dos Equipamentos</a>
    <a class="btn-export" href="{% url 'tipo' %}">Equipamentos por Tipo</a>
    <a class="btn-export" href="{% url 'marca' %}">Equipamentos por Marca</a>
    <a class="btn-export" href="{% url 'prioridade' %}">Prioridades de Chamadas</a>
    <a class="btn-export" href="{% url 'status' %}">Status das Chamadas</a>
</div>
<script src="{% static 'js/particles.js' %}"></script>
<script src="{% static 'js/load-particles.js' %}"></script>
{% endblock %}

main/templates/main/cadastrar_manutencoes.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Cadastrar Manutenções{% endblock %}

{% block content %}
<div id="particles-js"></div>
<div class="ativo-item">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="menu-container-details">
        <div class="menu-items">
            <a class="btn-inicio" href="{% url 'index' %}">Início</a>
            <a class="btn-inicio" href="{% url 'listar_ativos' %}">Equipamentos</a>
            <a class="btn-inicio" href="{% url 'listar_chamadas' %}">Chamadas</a>
        </div>
    </div>

    {% if form.errors %}
        <ul class="error">
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <div class="codigo">
        <h1>Cadastrar Múltiplas Manutenções</h1>
    </div>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn-login" type="submit">Cadastrar</button>
    </form>

    <script>
        $(function() {
            $("#id_data_inicio").datepicker({dateFormat: 'dd/mm/yy'});
            $("#id_data_conclusao").datepicker({dateFormat: 'dd/mm/yy'});
        });
        $(document).ready(function() {
            $('#id_ativos').select2();
        });
    </script>
</div>
<script src="{% static 'js/particles.js' %}"></script>
<script src="{% static 'js/load-particles.js' %}"></script>
{% endblock %}

main/templates/main/chart_associacao_equipamento_chamada.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Gráfico de Chamadas Associadas por Equipamento{% endblock %}

{% block content %}
<h1 class="title">Gráfico de Chamadas Associadas por Equipamento</h1>

<canvas id="associacaoEquipamentoChamadaChart" width="400" height="150"></canvas>

<script>
    var ctx = document.getElementById('associacaoEquipamentoChamadaChart').getContext('2d');
    var data = {
        labels: {{ labels|safe }},
        datasets: [{
            label: 'Quantidade de Associações',
            data: {{ counts|safe }},
            backgroundColor: 'rgba(75, 192, 192, 0.7)', // Cor de preenchimento
            borderColor: 'rgba(75, 192, 192, 1)',        // Cor da borda
            borderWidth: 1
        }]
    };

    var myChart = new Chart(ctx, {
        type: 'bar',
        data: data,
        options: {
            indexAxis: 'y',
            plugins: {
                legend: {
                    display: false // Para remover a legenda
                }
            },
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Quantidade de Associações',
                        font: {
                            size: 20,
                            family:'arial'
                        }
                    },
                    ticks: {
                        color: '#273E74',
                        font: {
                            size: 16,
                        }
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Equipamentos',
                        font: {
                            size: 20,
                            family:'arial'
                        }
                    },
                    ticks: {
                        color: '#273E74',
                        font: {
                            size: 16,
                        }
                    }
                }
            }
        }
    });
</script>
{% endblock %}

main/templates/main/chart_chamadas_por_sala.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Chamadas por Sala{% endblock %}

{% block content %}
<h1 class="title">Número de Chamadas por Sala</h1>

<div class="menu-container">
    <div class="menu-items">
        <a class="btn-inicio" href="{% url 'index' %}">Início</a>
        <a class="btn-inicio" href="{% url 'listar_ativos' %}">Equipamentos</a>
        <a class="btn-inicio" href="{% url 'listar_chamadas' %}">Chamadas</a>
    </div>
</div>
        
<canvas id="situacaoChart" width="400" height="150"></canvas>

<script>
    var ctx = document.getElementById('situacaoChart').getContext('2d');
    var data = {
        labels: [{% for data_point in sala_data %}"{{ data_point.label }}", {% endfor %}],
        datasets: [{
            label: 'Quantidade ',
            data: [{% for data_point in sala_data %}{{ data_point.count }}, {% endfor %}],
            backgroundColor: [
                'rgba(102, 26, 135, 0.7)', // Cor para 'Funcionando'
            ],
            borderColor: [
                'rgba(102, 26, 135, 1)',    
            ],
            borderWidth: 1
        }]
    };

    var myChart = new Chart(ctx, {
        type: 'bar',
        data: data,
        options: {
            plugins: {
                legend: {
                    display: false // Para remover a legenda
                }
            },
            indexAxis: 'y',
            scales: {
                x: {
                    ticks: {
                        color: '#273E74',
                        font: {
                            size: 25,
                        }
                    }
                },
                y: {
                    ticks: {
                        color: '#273E74',
                        font: {
                            size: 20 // Ajusta o tamanho do texto do eixo Y
                        }
                    }
                }
            }
        }
    });
</script>
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Tecnologia da Informação{% endblock %}

{% block content %}
    <div id="particles-js"></div>
    <div class="content">
        <img class="main-image" src="{% static 'images/logo.png' %}">
        <img style="width:130px" src="{% static 'images/icon.png' %}">
        <h1>Tecnologia da Informação</h1>
        <a href="{% url 'listar_chamadas' %}">Chamadas</a>  
        <a href="{% url 'listar_ativos' %}">Equipamentos</a>
        <a href="{% url 'admin:index' %}">Administrativo</a>
        <a href="{% url 'business_intelligence' %}">Business Intelligence</a>
        <a href="{% url 'importar_dados' %}">Importar Dados</a>
        <a href="{% url 'exportar_dados' %}">Exportar Dados</a>
        <a href="{% url 'logout' %}">Logout</a>        
    </div>
    <script src="{% static 'js/particles.js' %}"></script>
    <script src="{% static 'js/load-particles.js' %}"></script>
{% endblock %}